// --------- APPLICATIONS ---------
// Applications - list
export const APPLICATIONS_LIST_FETCHING = 'APPLICATIONS_LIST_FETCHING'
export const APPLICATIONS_LIST_RECEIVED = 'APPLICATIONS_LIST_RECEIVED'
export const APPLICATIONS_LIST_FAILED = 'APPLICATIONS_LIST_FAILED'

// Applications - names
export const APPLICATION_NAMES_REQUEST = 'APPLICATION_NAMES_REQUEST'
export const APPLICATION_NAMES_RECEIVED = 'APPLICATION_NAMES_RECEIVED'

// Application - Fasit-data
export const APPLICATION_FASIT_FETCHING = "APPLICATION_FASIT_FETCHING"
export const APPLICATION_FASIT_RECEIVED = "APPLICATION_FASIT_RECEIVED"
export const APPLICATION_FASIT_REQUEST_FAILED = "APPLICATION_FASIT_REQUEST_FAILED"
export const APPLICATION_FASIT_REQUEST = "APPLICATION_FASIT_REQUEST"

// Application - ApplicationInstances
export const APPLICATION_INSTANCES_REQUEST = 'APPLICATION_INSTANCES_REQUEST'
export const APPLICATION_INSTANCES_FETCHING = 'APPLICATION_INSTANCES_FETCHING'
export const APPLICATION_INSTANCES_RECEIVED = 'APPLICATION_INSTANCES_RECEIVED'
export const APPLICATION_INSTANCES_REQUEST_FAILED = 'APPLICATION_INSTANCES_REQUEST_FAILED'

// --------- AUTHENTICATION ---------
export const DISPLAY_LOGIN = 'DISPLAY_LOGIN'
export const GET_USER = 'GET_USER'
export const LOGIN = 'LOGIN'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGIN_SUBMITTED = 'LOGIN_SUBMITTED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'

// --------- CONFIGURATION ---------
// - Henter inn alle web-endepunkter som benyttes fra /config
export const RECEIVE_CONFIGURATION = 'RECEIVE_CONFIGURATION'
export const RECEIVE_CONFIGURATION_FAILED = 'RECEIVE_CONFIGURATION_FAILED'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

// --------- ENVIRONMENTS ---------
// Environments - list
export const ENVIRONMENTS_LIST_FETCHING = 'ENVIRONMENTS_LIST_FETCHING'
export const ENVIRONMENTS_LIST_RECEIVED = 'ENVIRONMENTS_LIST_RECEIVED'
export const ENVIRONMENTS_LIST_FAILED = 'ENVIRONMENTS_LIST_FAILED'

// Environment - names
export const ENVIRONMENTS_REQUEST = 'ENVIRONMENT_NAMES_REQUEST'
export const ENVIRONMENTS_RECEIVED = 'ENVIRONMENT_NAMES_RECEIVED'

// --------- COMMON ---------
// --------- REVISIONS ---------
export const SET_ACTIVE_REVISION = "SET_ACTIVE_REVISION"
export const REVISIONS_REQUEST = 'REVISIONS_REQUEST'
export const REVISIONS_FETCHING = 'REVISIONS_FETCHING'
export const REVISIONS_RECEIVED = 'REVISIONS_RECEIVED'
export const REVISIONS_REQUEST_FAILED = 'REVISIONS_REQUEST_FAILED'
export const REVISION_REQUEST = 'REVISION_REQUEST'
export const REVISION_FETCHING = 'REVISION_FETCHING'
export const REVISION_RECEIVED = 'REVISION_RECEIVED'
export const REVISION_REQUEST_FAILED = 'REVISION_REQUEST_FAILED'

// --------- SEARCH ---------
export const FETCH_ELEMENT_LISTS = 'SUBMIT_SEARCH_STRING'
export const CHANGE_FILTER = 'CHANGE_FILTER'
export const SET_SEARCH_CONTEXT = 'SET_SEARCH_CONTEXT'
export const SET_SEARCH_STRING = 'SET_SEARCH_STRING'

// --------- SUBMIT FORM ---------
export const SUBMIT_FORM = 'SUBMIT_FORM'
export const SUBMITTING_FORM = 'SUBMITTING_FORM'
export const SUBMIT_FORM_SUCCESS = 'SUBMIT_FORM_SUCCESS'
export const SUBMIT_FORM_FAILED = 'SUBMIT_FORM_FAILED'
export const CLOSE_SUBMIT_FORM_STATUS = 'CLOSE_SUBMIT_FORM_STATUS'


// --------- INSTANCES ---------
// Instances - list
export const INSTANCES_LIST_FETCHING = 'INSTANCES_LIST_FETCHING'
export const INSTANCES_LIST_RECEIVED = 'INSTANCES_LIST_RECEIVED'
export const INSTANCES_LIST_FAILED = 'INSTANCES_LIST_FAILED'

// Instance
export const INSTANCE_FASIT_REQUEST = 'INSTANCE_FASIT_REQUEST'
export const INSTANCE_FASIT_FETCHING = 'INSTANCE_FASIT_FETCHING'
export const INSTANCE_FASIT_RECEIVED = 'INSTANCE_FASIT_RECEIVED'
export const INSTANCE_FASIT_REQUEST_FAILED = 'INSTANCE_FASIT_REQUEST_FAILED'

// --------- NODES ---------
// Nodes - list
export const CHANGE_PAGE = 'CHANGE_PAGE'
export const NODES_LIST_FETCHING = 'NODES_LIST_FETCHING'
export const NODES_LIST_RECEIVED = 'NODES_LIST_RECEIVED'
export const NODES_LIST_FAILED = 'NODES_LIST_FAILED'

// NodeTypes
export const NODE_TYPES_REQUEST = 'NODE_TYPES_REQUEST'
export const NODE_TYPES_RECEIVED = 'NODE_TYPES_RECEIVED'

// Node - Events
export const NODE_EVENTS_REQUEST = 'NODE_EVENTS_REQUEST'
export const NODE_EVENTS_FETCHING = 'NODE_EVENTS_FETCHING'
export const NODE_EVENTS_RECEIVED = 'NODE_EVENTS_RECEIVED'
export const NODE_EVENTS_REQUEST_FAILED = 'NODE_EVENTS_REQUEST_FAILED'

// Node - SERA
export const NODE_SERA_REQUEST = 'NODE_SERA_REQUEST'
export const NODE_SERA_FETCHING = 'NODE_SERA_FETCHING'
export const NODE_SERA_RECEIVED = 'NODE_SERA_RECEIVED'
export const NODE_SERA_REQUEST_FAILED = 'NODE_SERA_REQUEST_FAILED'

// Node - Fasit data
export const CLEAR_NODE_PASSWORD = 'CLEAR_NODE_PASSWORD'
export const NODE_FASIT_FETCHING = 'NODE_FASIT_FETCHING'
export const NODE_FASIT_PASSWORD_RECEIVED = 'NODE_FASIT_PASSWORD_RECEIVED'
export const NODE_FASIT_PASSWORD_REQUEST = 'NODE_FASIT_PASSWORD_REQUEST'
export const NODE_FASIT_PASSWORD_REQUEST_FAILED = 'NODE_FASIT_PASSWORD_REQUEST_FAILED'
export const NODE_FASIT_RECEIVED = 'NODE_FASIT_RECEIVED'
export const NODE_FASIT_REQUEST = 'NODE_FASIT_REQUEST'
export const NODE_FASIT_REQUEST_FAILED = 'NODE_FASIT_REQUEST_FAILED'
export const SHOW_NODE_PASSWORD = 'SHOW_NODE_PASSWORD'

// Node - Create new Fasit node
export const SHOW_NEW_NODE_FORM = 'SHOW_NEW_NODE_FORM'

// Node - Lifecycle - rescue node
export const RESCUE_NODE = 'RESCUE_NODE'

// --------- RESOURCES ---------
// Resources - list
export const RESOURCES_LIST_FETCHING = 'RESOURCES_LIST_FETCHING'
export const RESOURCES_LIST_RECEIVED = 'RESOURCES_LIST_RECEIVED'
export const RESOURCES_LIST_FAILED = 'RESOURCES_LIST_FAILED'

// ResourceTypes
export const RESOURCE_TYPES_REQUEST = 'RESOURCE_TYPES_REQUEST'
export const RESOURCE_TYPES_RECEIVED = 'RESOURCE_TYPES_RECEIVED'

// Resource - Fasit
export const RESOURCE_FASIT_REQUEST = 'RESOURCE_FASIT_REQUEST'
export const RESOURCE_FASIT_FETCHING = 'RESOURCE_FASIT_FETCHING'
export const RESOURCE_FASIT_RECEIVED = 'RESOURCE_FASIT_RECEIVED'
export const RESOURCE_FASIT_REQUEST_FAILED = 'RESOURCE_FASIT_REQUEST_FAILED'

