
name: 'Merge Master to Sandbox'

on:
  push:
    branches:
      - master

jobs:
  mergeMainToSandbox:
    permissions:
      contents: "write"
      checks: "write"
      id-token: "write"
      packages: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 20
      - name: Merge Master to Sandbox
        uses: robotology/gh-action-nightly-merge@v1.5.2
        with:
          stable_branch: 'master'
          development_branch: 'sandbox'
          allow_ff: true
          allow_forks: true
          user_name: GitHub Merge Actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  call-buildAndDeploySandbox:
    needs: mergeMainToSandbox
    permissions:
      contents: "read"
      checks: "write"
      id-token: "write"
      packages: "write"
    secrets: inherit
    uses: ./.github/workflows/deploy-sandbox.yml
